POST http://localhost:5050/api/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123123",
    "firstName": "van",
    "lastName": "tien",
    "status": "not activated",
    "position": "user"
}

###

POST http://localhost:5050/api/auth/login
Content-Type: application/json

{
    "email": "shop@gmail.com",
    "password": "123123"
}

###

POST http://localhost:5050/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQyYzYwNThkMjM4YWMyNGY0OWVkMTMiLCJpYXQiOjE2NDEyNjQ3Mjd9.lZ8q5G8y0Zw_ZQ0wCu3m_Rfbk5_3q8HvSQtSWGmadig

{
    "pro_name": "Desk",
    "pro_slug": "ghe",
    "pro_price": "120000",
    "pro_quantity": "31",
    "pro_description": "ghe tre",
    "pro_avatar": ""
}

###

GET  http://localhost:5050/api/products/all
###

GET  http://localhost:5050/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQyYzYwNThkMjM4YWMyNGY0OWVkMTMiLCJpYXQiOjE2NDEyNjQ3Mjd9.lZ8q5G8y0Zw_ZQ0wCu3m_Rfbk5_3q8HvSQtSWGmadig

###

PUT http://localhost:5050/api/products/61d17de40ef56005d2fd18a2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQyYzYwNThkMjM4YWMyNGY0OWVkMTMiLCJpYXQiOjE2NDEyNjQ3Mjd9.lZ8q5G8y0Zw_ZQ0wCu3m_Rfbk5_3q8HvSQtSWGmadig

{
    "pro_name": "Desk",
    "pro_slug": "ghe",
    "pro_price": "190000",
    "pro_quantity": "11",
    "pro_description": "updated12",
    "pro_avatar": "updated12"
}

###

DELETE  http://localhost:5050/api/products/61d17de40ef56005d2fd18a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQyYzYwNThkMjM4YWMyNGY0OWVkMTMiLCJpYXQiOjE2NDEyNjQ3Mjd9.lZ8q5G8y0Zw_ZQ0wCu3m_Rfbk5_3q8HvSQtSWGmadig
